<?php

namespace ContainerGr3eG0e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Op_RMlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._op.rMl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._op.rMl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'newsRepository' => ['privates', 'App\\Repository\\NewsRepository', 'getNewsRepositoryService', true],
        ], [
            'newsRepository' => 'App\\Repository\\NewsRepository',
        ]);
    }
}
