<?php

namespace ContainerGr3eG0e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5Tqu3JjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5Tqu3Jj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5Tqu3Jj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'news' => ['privates', '.errored..service_locator.5Tqu3Jj.App\\Entity\\News', NULL, 'Cannot autowire service ".service_locator.5Tqu3Jj": it references class "App\\Entity\\News" but no such service exists.'],
            'newsRepository' => ['privates', 'App\\Repository\\NewsRepository', 'getNewsRepositoryService', true],
        ], [
            'news' => 'App\\Entity\\News',
            'newsRepository' => 'App\\Repository\\NewsRepository',
        ]);
    }
}
