<?php

namespace ContainerGr3eG0e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QdefuDkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qdefuDk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qdefuDk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.bw8tvv2', 'get_ServiceLocator_Bw8tvv2Service', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.bw8tvv2', 'get_ServiceLocator_Bw8tvv2Service', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\CategoryController::new' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.7P87fGM', 'get_ServiceLocator_7P87fGMService', true],
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.OW8jEgK', 'get_ServiceLocator_OW8jEgKService', true],
            'App\\Controller\\HomepageController::NewsByCategory' => ['privates', '.service_locator.afULyJO', 'get_ServiceLocator_AfULyJOService', true],
            'App\\Controller\\HomepageController::index' => ['privates', '.service_locator._op.rMl', 'get_ServiceLocator_Op_RMlService', true],
            'App\\Controller\\HomepageController::newsShow' => ['privates', '.service_locator.iK7dpsS', 'get_ServiceLocator_IK7dpsSService', true],
            'App\\Controller\\NewsController::delete' => ['privates', '.service_locator.5Tqu3Jj', 'get_ServiceLocator_5Tqu3JjService', true],
            'App\\Controller\\NewsController::edit' => ['privates', '.service_locator.5Tqu3Jj', 'get_ServiceLocator_5Tqu3JjService', true],
            'App\\Controller\\NewsController::index' => ['privates', '.service_locator._op.rMl', 'get_ServiceLocator_Op_RMlService', true],
            'App\\Controller\\NewsController::new' => ['privates', '.service_locator._op.rMl', 'get_ServiceLocator_Op_RMlService', true],
            'App\\Controller\\NewsController::show' => ['privates', '.service_locator.MCw.l9M', 'get_ServiceLocator_MCw_L9MService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.q2ji3lu', 'get_ServiceLocator_Q2ji3luService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.kdKsWx5', 'get_ServiceLocator_KdKsWx5Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.bw8tvv2', 'get_ServiceLocator_Bw8tvv2Service', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.bw8tvv2', 'get_ServiceLocator_Bw8tvv2Service', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\CategoryController:new' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.7P87fGM', 'get_ServiceLocator_7P87fGMService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.OW8jEgK', 'get_ServiceLocator_OW8jEgKService', true],
            'App\\Controller\\HomepageController:NewsByCategory' => ['privates', '.service_locator.afULyJO', 'get_ServiceLocator_AfULyJOService', true],
            'App\\Controller\\HomepageController:index' => ['privates', '.service_locator._op.rMl', 'get_ServiceLocator_Op_RMlService', true],
            'App\\Controller\\HomepageController:newsShow' => ['privates', '.service_locator.iK7dpsS', 'get_ServiceLocator_IK7dpsSService', true],
            'App\\Controller\\NewsController:delete' => ['privates', '.service_locator.5Tqu3Jj', 'get_ServiceLocator_5Tqu3JjService', true],
            'App\\Controller\\NewsController:edit' => ['privates', '.service_locator.5Tqu3Jj', 'get_ServiceLocator_5Tqu3JjService', true],
            'App\\Controller\\NewsController:index' => ['privates', '.service_locator._op.rMl', 'get_ServiceLocator_Op_RMlService', true],
            'App\\Controller\\NewsController:new' => ['privates', '.service_locator._op.rMl', 'get_ServiceLocator_Op_RMlService', true],
            'App\\Controller\\NewsController:show' => ['privates', '.service_locator.MCw.l9M', 'get_ServiceLocator_MCw_L9MService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.q2ji3lu', 'get_ServiceLocator_Q2ji3luService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.kdKsWx5', 'get_ServiceLocator_KdKsWx5Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::new' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\HomepageController::NewsByCategory' => '?',
            'App\\Controller\\HomepageController::index' => '?',
            'App\\Controller\\HomepageController::newsShow' => '?',
            'App\\Controller\\NewsController::delete' => '?',
            'App\\Controller\\NewsController::edit' => '?',
            'App\\Controller\\NewsController::index' => '?',
            'App\\Controller\\NewsController::new' => '?',
            'App\\Controller\\NewsController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:new' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\HomepageController:NewsByCategory' => '?',
            'App\\Controller\\HomepageController:index' => '?',
            'App\\Controller\\HomepageController:newsShow' => '?',
            'App\\Controller\\NewsController:delete' => '?',
            'App\\Controller\\NewsController:edit' => '?',
            'App\\Controller\\NewsController:index' => '?',
            'App\\Controller\\NewsController:new' => '?',
            'App\\Controller\\NewsController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
