<?php

namespace ContainerGr3eG0e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IK7dpsSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iK7dpsS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iK7dpsS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'newsRepository' => ['privates', 'App\\Repository\\NewsRepository', 'getNewsRepositoryService', true],
        ], [
            'commentRepository' => 'App\\Repository\\CommentRepository',
            'entityManager' => '?',
            'newsRepository' => 'App\\Repository\\NewsRepository',
        ]);
    }
}
