<?php

namespace ContainerGr3eG0e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNavCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\NavCategory' shared autowired service.
     *
     * @return \App\Service\NavCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/NavCategory.php';

        return $container->privates['App\\Service\\NavCategory'] = new \App\Service\NavCategory(($container->privates['App\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepositoryService')));
    }
}
